# Generated by Django 4.0.4 on 2022-06-01 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField()),
                ('name', models.CharField(max_length=20)),
                ('email', models.TextField()),
                ('school', models.TextField()),
                ('department', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FolderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('max_volume', models.PositiveIntegerField()),
                ('volume', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('0', 'CLASS_ROOM'), ('1', 'LECTURE'), ('2', 'ASSIGNMENT')], default=1, max_length=1)),
                ('made_by', models.ForeignKey(db_column='made_by', on_delete=django.db.models.deletion.CASCADE, related_name='make', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Folder_User_Relationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.ForeignKey(db_column='folder_id', on_delete=django.db.models.deletion.CASCADE, related_name='match', to='app.folderitems')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='match', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ['folder_id'],
            },
        ),
        migrations.CreateModel(
            name='Folder_File_Relationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.PositiveIntegerField()),
                ('name', models.TextField()),
                ('is_folder', models.BooleanField()),
                ('child_type', models.CharField(choices=[('0', 'CLASS_ROOM'), ('1', 'LECTURE'), ('2', 'ASSIGNMENT')], default=1, max_length=1, null=True)),
                ('parent', models.ForeignKey(db_column='parent', on_delete=django.db.models.deletion.CASCADE, related_name='have', to='app.folderitems')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
