# Generated by Django 4.0.4 on 2022-05-21 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('pw', models.CharField(max_length=20)),
                ('is_student', models.BooleanField()),
                ('name', models.CharField(max_length=20)),
                ('email', models.TextField()),
                ('school', models.TextField()),
                ('department', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['u_id'],
            },
        ),
    ]
