# Generated by Django 4.0.4 on 2022-05-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('pw', models.CharField(max_length=20)),
                ('is_student', models.BooleanField()),
                ('name', models.CharField(max_length=20)),
                ('email', models.TextField()),
                ('school', models.TextField()),
                ('department', models.TextField()),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
